inherit_from: .rubocop_todo.yml

AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.6

Layout/EndAlignment:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - "bin/**/*"

Style/SignalException:
  EnforcedStyle: semantic

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
